// Sample data — Martina's roster.
// Covers all 5 archetypes from the brief.

const CLIENTS = [
  {
    id: 'daniel-costa',
    name: 'Daniel Costa',
    initials: 'DC',
    avatarTone: 'ink',
    phone: '+359 88 421 0918',
    age: 31,
    ntrp: 5.0,
    archetype: 'Adult · Advanced',
    style: 'All-courter',
    grip: 'Eastern · Two-handed BH',
    handed: 'Right-handed',
    gear: 'Babolat Pure Aero · 16x19 · 330 g',
    preferences: 'Wants serious technical feedback. Prefers 90-min sessions. Will play in rain.',
    lastLesson: '2 days ago',
    lastLessonAt: 'Tue, May 19 · 17:30',
    nextLesson: 'Thu, May 28 · 17:30',
    cadence: 'Twice weekly',
    notes: [
      { at: 'Tue, May 19 · 18:48', body: 'Backhand return on deuce side dipping into net — opens shoulder too early. Cued split-step on toss recognition. Better by end.' },
      { at: 'Sat, May 16 · 09:12', body: 'Serve speed up ~8mph after platform-stance tweak. Slice serve out-wide is now a real weapon. Don’t lose it.' },
      { at: 'Thu, May 14 · 17:35', body: 'Wants to drill kick serve for the Plovdiv tournament. Three weeks out.' },
      { at: 'Tue, May 12 · 17:55', body: 'Fitness fine. Footwork on the run-around forehand still adjusts late. Run shadow patterns next session.' },
    ],
  },
  {
    id: 'charlotte-whitfield-hayes',
    name: 'Charlotte Whitfield-Hayes',
    initials: 'CW',
    avatarTone: 'default',
    phone: '+44 7700 900 184',
    age: 38,
    ntrp: 3.5,
    archetype: 'Adult · Intermediate',
    style: 'Social · Volleyer',
    grip: 'Continental serve · Eastern FH',
    handed: 'Right-handed',
    gear: 'Wilson Clash 100 · 16x19 · 295 g',
    preferences: 'Here for the people, not the trophy. Loves doubles drills. Will bring a friend. Keep it light, keep it fun.',
    lastLesson: 'Yesterday',
    lastLessonAt: 'Mon, May 20 · 11:00',
    nextLesson: 'Mon, May 27 · 11:00',
    cadence: 'Weekly · Mondays',
    notes: [
      { at: 'Mon, May 20 · 12:08', body: 'Brought Pippa again — net play drills both. Charlotte’s touch volleys actually pretty good when she stops thinking.' },
      { at: 'Mon, May 13 · 12:02', body: 'Asked about the club mixer next month — confirmed both for Saturday slot.' },
      { at: 'Mon, May 6 · 12:00', body: 'Hated the baseline conditioning, loved the king-of-the-court doubles. Note for future planning.' },
    ],
  },
  {
    id: 'eleni-vasilakos',
    name: 'Eleni Vasilakos',
    initials: 'EV',
    avatarTone: 'default',
    phone: '+30 694 558 2210',
    age: 42,
    ntrp: 2.0,
    archetype: 'Adult · Beginner',
    style: 'Recreational',
    grip: 'Eastern FH (learning)',
    handed: 'Right-handed',
    gear: 'Borrowed club racquet · Head Ti.S6',
    preferences: 'Wants to get outside, build a habit. No tournaments, no pressure. Encouragement matters more than correction.',
    lastLesson: '5 days ago',
    lastLessonAt: 'Fri, May 16 · 18:00',
    nextLesson: 'Fri, May 29 · 18:00',
    cadence: 'Weekly · Fridays',
    notes: [
      { at: 'Fri, May 16 · 18:55', body: 'First rally past 6 balls today — was visibly thrilled. Build on that. Keep targets achievable.' },
      { at: 'Fri, May 9 · 18:50', body: 'Grip slipping back to frying-pan under pressure. Tape the racquet for visual reference.' },
    ],
  },
  {
    id: 'theo-marchetti',
    name: 'Theo Marchetti',
    initials: 'TM',
    avatarTone: 'clay',
    phone: '+39 333 412 9087 · (Sofia, mum)',
    age: 5,
    ntrp: null,
    archetype: 'Junior · Red ball',
    style: 'First sessions',
    grip: 'N/A — foam ball, hand-feed',
    handed: 'Right-handed (probably)',
    gear: 'Mini racquet (parent owns) · foam balls (mine)',
    preferences: 'Max 30 min. Loves the "rabbit run" warm-up. Bring stickers. Treat-based reward kept session two together.',
    lastLesson: '3 days ago',
    lastLessonAt: 'Sat, May 18 · 10:00',
    nextLesson: 'Sat, May 25 · 10:00',
    cadence: 'Weekly · Sat mornings',
    notes: [
      { at: 'Sat, May 18 · 10:33', body: 'Tracked the ball with his eyes for a full minute today. That is huge. Sofia happy.' },
      { at: 'Sat, May 11 · 10:30', body: 'Lost interest at ~22 min. Lesson 2 ended early — fine. Don’t push it.' },
      { at: 'Sat, May 4 · 10:30', body: 'First session. Mostly tag and "find the cone". Goal was: come back next week. Did.' },
    ],
  },
  {
    id: 'henley-juniors',
    name: 'Henley Juniors',
    initials: 'HJ',
    avatarTone: 'clay',
    phone: '+44 7700 902 441 · (Mark Henley, parent coord)',
    age: null,
    ntrp: null,
    archetype: 'Group · 4 kids',
    style: 'Ages 7, 7, 9, 10',
    grip: 'Mixed',
    handed: 'Mixed',
    gear: 'Orange & green balls · club racquets',
    preferences: 'Parents organised this together. Wednesday afternoons. Keep it active — boredom is the enemy. Game-based.',
    lastLesson: '6 days ago',
    lastLessonAt: 'Wed, May 14 · 16:00',
    nextLesson: 'Wed, May 28 · 16:00',
    cadence: 'Weekly · Wednesdays',
    members: ['Olive (10)', 'Sam (9)', 'Theo H. (7)', 'Iris (7)'],
    notes: [
      { at: 'Wed, May 14 · 17:08', body: 'Iris is finally swinging across the body, not pushing. Sam is bored — needs harder targets. Split next week.' },
      { at: 'Wed, May 7 · 17:05', body: '"World cup" round-robin worked. Do again. Olive won, very proud.' },
    ],
  },
  {
    id: 'margot-beaumont',
    name: 'Margot Beaumont',
    initials: 'MB',
    avatarTone: 'default',
    phone: '+33 6 18 22 47 03',
    age: 29,
    ntrp: 4.5,
    archetype: 'Adult · Advanced',
    style: 'Baseliner · Heavy topspin',
    grip: 'Semi-Western FH · Two-handed BH',
    handed: 'Right-handed',
    gear: 'Yonex VCORE 98 · 305 g · Poly main',
    preferences: 'Match prep oriented. Wants live-ball drills and pattern repetition. Hates fitness theatre — wants tennis fitness.',
    lastLesson: 'Today',
    lastLessonAt: 'Wed, May 21 · 08:00',
    nextLesson: 'Sat, May 24 · 08:00',
    cadence: 'Twice weekly',
    notes: [
      { at: 'Wed, May 21 · 09:18', body: 'Crosscourt-deep / inside-out forehand pattern — clean 7/10 reps once she committed. Stop hedging the second ball.' },
      { at: 'Sat, May 17 · 09:15', body: 'Serve toss drifting back-and-left on second serve. Toss-from-a-shelf drill helped briefly.' },
    ],
  },
  {
    id: 'ravi-patel',
    name: 'Ravi Patel',
    initials: 'RP',
    avatarTone: 'default',
    phone: '+44 7911 482 003',
    age: 34,
    ntrp: 3.0,
    archetype: 'Adult · Intermediate',
    style: 'Counterpuncher',
    grip: 'Eastern FH · One-handed BH (learning slice)',
    handed: 'Right-handed',
    gear: 'Head Speed MP · 16x19 · 300 g',
    preferences: 'Engineer brain — likes the "why". Send drill PDFs. He will study them.',
    lastLesson: '4 days ago',
    lastLessonAt: 'Sat, May 17 · 14:00',
    nextLesson: 'Sat, May 24 · 14:00',
    cadence: 'Weekly · Saturdays',
    notes: [
      { at: 'Sat, May 17 · 15:10', body: 'Slice backhand finally has carry — keep it low. Footwork still wide on approach.' },
    ],
  },
  {
    id: 'alex-kim',
    name: 'Alex Kim',
    initials: 'AK',
    avatarTone: 'default',
    phone: '+1 408 555 0193 · (Min, dad)',
    age: 14,
    ntrp: 4.0,
    archetype: 'Junior · Competitive',
    style: 'Aggressive baseliner',
    grip: 'Semi-Western · Two-handed BH',
    handed: 'Left-handed',
    gear: 'Wilson Blade 98 · 16x19 · 305 g',
    preferences: 'Tournament track. Dad sits courtside. Parent dynamic real — communicate plan in writing after each session.',
    lastLesson: '3 days ago',
    lastLessonAt: 'Sat, May 18 · 15:30',
    nextLesson: 'Sat, May 25 · 15:30',
    cadence: 'Weekly · Saturdays',
    notes: [
      { at: 'Sat, May 18 · 16:40', body: 'Lefty serve out-wide on ad side — when he commits, untouchable. He doesn’t commit enough.' },
    ],
  },
];

// Today’s schedule — week view friendly.
// "Today" is Wed May 21 2026 in this prototype.
const TODAY_LABEL = 'Wednesday, May 21';

const SCHEDULE = [
  // Today
  { day: 'today', date: '21', month: 'May', start: '08:00', end: '09:30', duration: 90, clientId: 'margot-beaumont', status: 'done',     court: 'Court 3 · Club' },
  { day: 'today', date: '21', month: 'May', start: '11:00', end: '12:00', duration: 60, clientId: 'charlotte-whitfield-hayes', status: 'done',    court: 'Court 1 · Club' },
  { day: 'today', date: '21', month: 'May', start: '17:30', end: '19:00', duration: 90, clientId: 'daniel-costa',    status: 'upcoming', court: 'Court 3 · Club' },
  // Tomorrow
  { day: 'tomorrow', date: '22', month: 'May', start: '07:30', end: '08:30', duration: 60, clientId: 'ravi-patel',     status: 'scheduled', court: 'Court 2 · Club' },
  { day: 'tomorrow', date: '22', month: 'May', start: '15:30', end: '16:30', duration: 60, clientId: 'alex-kim',       status: 'scheduled', court: 'Court 3 · Club' },
  // Sat
  { day: 'sat',  date: '24', month: 'May', start: '08:00', end: '09:30', duration: 90, clientId: 'margot-beaumont', status: 'scheduled', court: 'Court 3 · Club' },
  { day: 'sat',  date: '24', month: 'May', start: '15:30', end: '16:30', duration: 60, clientId: 'alex-kim',       status: 'scheduled', court: 'Court 3 · Club' },
];

const DRILLS_FALLBACK = {
  forehand: {
    warmup:    { name: 'Mini-court rallies, cross-court',          desc: 'Service-box only · feet, racquet face, finish' },
    technical: { name: 'Inside-out forehand · spot feed',          desc: 'Deuce ad-court target · 3 sets × 10 · prep early' },
    tactical:  { name: 'Crosscourt deep / inside-out attack',      desc: 'Live ball · 2nd-ball aggression · 4-ball patterns' },
    finish:    { name: '"Spanish X" footwork · 4 cones',           desc: 'Forehand-only · 3 × 90s · breathing, recovery hops' },
  },
  backhand: {
    warmup:    { name: 'Backhand pat-ups, mini rally',             desc: 'Loose grip · early take-back · contact in front' },
    technical: { name: 'Two-hander down-the-line',                 desc: 'Spot feed · 3 × 10 each side · shoulder rotation' },
    tactical:  { name: 'Slice approach + first volley',            desc: 'Live ball · low slice, close to net · split-step' },
    finish:    { name: 'King-of-the-court · backhand only',        desc: '4 players or shadow · 12 min · point play' },
  },
  serve: {
    warmup:    { name: 'Shadow serves + ball drops',               desc: 'Trophy pose · toss-and-catch × 20 · then live' },
    technical: { name: 'Kick serve · target boxes',                desc: 'Ad-side T · 3 × 8 · brush up, pronate, finish left' },
    tactical:  { name: 'Serve + 1 patterns',                       desc: 'Wide / body / T · plan the +1 before toss' },
    finish:    { name: 'First-serve % game to 11',                 desc: 'Make 2, score; miss, opponent scores' },
  },
  footwork: {
    warmup:    { name: 'Ladder + dynamic',                         desc: 'Quick feet × 4 patterns · 5 min flow' },
    technical: { name: 'Recovery footwork · 5-cone',               desc: 'Forehand → recover → backhand · 3 × 8' },
    tactical:  { name: 'Two-on-one wide-ball coverage',            desc: 'Live ball · forced movement · 12 min' },
    finish:    { name: 'Suicide sprints to net & back',            desc: '4 × 30s · 30s rest · racquet in hand' },
  },
  fitness: {
    warmup:    { name: 'Dynamic mobility + 2 min jog',             desc: 'Hips, ankles, shoulders · easy' },
    technical: { name: 'Rally to 20 · controlled pace',            desc: 'No winners · build the engine' },
    tactical:  { name: 'Live ball · longer points only count',     desc: 'Points <4 shots = replay · 20 min' },
    finish:    { name: '"Around the world" + cool down',           desc: 'Touch each line, then 5-min walk' },
  },
};

window.CLIENTS = CLIENTS;
window.SCHEDULE = SCHEDULE;
window.TODAY_LABEL = TODAY_LABEL;
window.DRILLS_FALLBACK = DRILLS_FALLBACK;
